version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@1.5.0

jobs:
  build:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - gcp-cli/initialize
      - run: curl -sLO https://github.com/swagger-api/swagger-ui/archive/v3.23.3.tar.gz
      - run: tar zxf v3.23.3.tar.gz
      - run: cp -r swagger-ui-3.23.3/dist/* swagger-ui
      - run: mkdir swagger-ui/api-docs
      - run: cp swagger.yaml swagger-ui/api-docs
      - run: gcloud app deploy swagger-ui/app.yaml
