runtime: go
api_version: go1

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /(.*\.html)$
  static_files: \1
  upload: .*\.html$
- url: /(.*\.css)$
  static_files: \1
  upload: .*\.css$
- url: /(.*\.js)$
  static_files: \1
  upload: .*\.js$
- url: /(.*\.png)$
  static_files: \1
  upload: .*\.png$
- url: /api-docs/swagger.yaml
  static_files: api-docs/swagger.yaml
  upload: api-docs/swagger.yaml
- url: /.*
  script: _go_app
